---
title: "Description of p_hacking_pm Repository Contents"
author: "Cynthia M. Kroeger"
date: "31 August 2018"
output: github_document
---

This repository contains supporting materials for conference abstracts published on our work evaluating p-hacking in PubMed. Each folder herein contains supporting materials for each publication, respectively. 


## Description of Folders:

* __conference_materials_2014__: Supporting materials for published conference abstract: Kroeger CM, Brown AW, Allison DB. Evidence of p-value fiddling using a rapid, high-volume, systematic method. American Society for Nutrition (ASN): Advances and Controversies in Clinical Nutrition Annual Scientific Meeting. National Harbor, Maryland, USA, 2014. 
* __conference_materials_2016__: Supporting materials for published conference abstract: Kroeger CM, Brown AW, Allison DB. Simple text-mining to detect comparative p-hacking is sensitive to text searching variations. The Obesity Society (TOS): Annual Scientific Meeting. New Orleans, Louisiana, USA, 2016.
* __conference_materials_2017__: Supporting materials for published conference abstract: Kroeger CM, Brown AW, Allison DB. Use of text-mining and comparative analysis to detect p-hacking in dietary supplement scientific literature. 5th Workshop on Biostatistics and Bioinformatics. Atlanta, Georgia, USA. 2017. 


## Description of Folder Contents 

The types of supporting materials in each folder include: 

* .md/.Rmd file that includes: description of the project, methodological details, descriptions of data and code variables, tips for replication, author contribution and contact information, funding information, and recommended citation information
* .csv file of the data collected 
* .R file with the analysis code
* .pdf file of the associated presentation (e.g., poster and/or slides)
* .txt file with licensing information
* Other supporting materials to help explain and improve the reproducibility of our methods 


## Recommendations for Citation of Supporting Materials  

* __Recommended citation for conference_materials_2014__: Kroeger CM, Brown AW. Data and analysis code for published abstract: Evidence of p-value fiddling using a rapid, high-volume, systematic method. Zenodo. 2018. DOI: 10.5281/zenodo.1406860 
* __Recommended citation for conference_materials_2016__: Kroeger CM, Brown AW. Data and analysis code for published abstract: Simple text-mining to detect comparative p-hacking is sensitive to text searching variations. Zenodo. 2018. DOI: 10.5281/zenodo.1406882 
* __Recommended citation for conference_materials_2017__: Kroeger CM, Brown AW. Data and analysis code for published abstract: Use of text-mining and comparative analysis to detect p-hacking in dietary supplement scientific literature. Zenodo. 2018. DOI:  
