---
title: "Conference Materials 2014"
author: "Cynthia M. Kroeger, Andrew W. Brown"
date: "8/31/2018"
output: github_document
---

## Project Description 

This project was implemented to collect preliminary data for a postdoctoral grant application (F32DK107157) to study common biases and statistical mistakes made in nutrition and obesity research. One such bias is p-hacking. As the poster describes in more detail, this project tested a rapid and high-volume method for detecting p-hacking in scientific literature. This was the start of a larger project, that has since been further developed and presented on. A manuscript with fully-developed methods is now being developed for publication. 


## Conference Description 

This work was presented at the American Society for Nutrition (ASN): Advances and Controversies in Clinical Nutrition Annual Scientific Meeting, in National Harbor, Maryland, USA, in 2014. 


## Contact Information for Principal Investigator and Corresponding Author

Cynthia M. Kroeger, PhD, Postdoctoral Fellow, Charles Perkins Centre, School of Pharmacy, Faculty of Medicine and Health, The University of Sydney. cynthia.kroeger@sydney.edu.au 


At the time of presentation, Dr. Kroeger was a PhD student at The University of Illinois at Chicago.


## Description of Supporting Materials 

### Presentation

This work was presented as a poster. 


__File name for poster:__ conference_materials_2014_poster.pdf


### Data

__File name for dataset:__ conference_materials_2014_data.csv


__Full names and definitions of column headings__

Column Heading      | Definition                            | Possible Values 
------------------- | ------------------------------------- | ----------------------
trial               | study trial                           | org = original trial
method              | search string method                  | a = method a 
database            | database data were collected from     | pm = PubMed
date                | date data were collected              |
mode                | mode of data extraction               | man = manual extraction 
three_common        | number of abstracts containing p = 0.03* and a common statistical term and NOT p = 0.04\*, p = 0.05\*, p = 0.06\*, or an atypical term|
four_common         | number of abstracts containing p = 0.04* and a common statistical term and NOT p = 0.03\*, p = 0.05\*, p = 0.06\*, or an atypical term |
five_common         | number of abstracts containing p = 0.05* and a common statistical term and NOT p = 0.03\*, p = 0.04\*, p = 0.06\*, or an atypical term |
six_common          | number of abstracts containing p = 0.06* and a common statistical term and NOT p = 0.03\*, p = 0.05\*, p = 0.04\*, or an atypical term |
three_atypical      | number of abstracts containing p = 0.03* and an atypical statistical term and NOT p = 0.04\*, p = 0.05\*, p = 0.06\*, or a common term |
four_atypical       | number of abstracts containing p = 0.04* and an atypical statistical term and NOT p = 0.03\*, p = 0.05\*, p = 0.06\*, or a common term |
five_atypical       | number of abstracts containing p = 0.05* and an atypical statistical term and NOT p = 0.03\*, p = 0.04\*, p = 0.06\*, or a common term |
six_atypical        | number of abstracts containing p = 0.06* and an atypical statistical term and NOT p = 0.03\*, p = 0.04\*, p = 0.05\*, or a common term |


*Methods are described in section "Methodological details" below.


Data were collected and formatted by Dr. Kroeger. 


### Methodological details

__Search string details for method a__

```{r}
# p-value bin 0.03: (p=.03*[tiab] OR p=0.03*[tiab])
# p-value bin 0.04: (p=.04*[tiab] OR p=0.04*[tiab])
# p-value bin 0.05: (p 05,05[tiab] OR p 050[tiab] OR p 0500[tiab] OR p 05006[tiab] OR p 0501[tiab] OR p 0501a[tiab] OR p 0502[tiab] OR p 0505[tiab] OR p 0507[tiab] OR p 051[tiab] OR p 0511[tiab] OR p 0513[tiab] OR p 0514[tiab] OR p 0515[tiab] OR p 0518[tiab] OR p 0519[tiab] OR p 052[tiab] OR p 0529[tiab] OR p 053[tiab] OR p 0537[tiab] OR p 054[tiab] OR p 0542[tiab] OR p 055[tiab] OR p 0557[tiab] OR p 056[tiab] OR p 0566[tiab] OR p 057[tiab] OR p 0571[tiab] OR p 0573[tiab] OR p 058[tiab] OR p 0583[tiab] OR p 0585[tiab] OR p 0588[tiab] OR p 059[tiab] OR p 0591[tiab] OR p 0594[tiab] OR p 0595[tiab] OR p 0597[tiab]) OR (p 0 05,15[tiab] OR p 0 05,863[tiab] OR p 0 05,95[tiab] OR p 0 050[tiab] OR p 0 0500[tiab] OR p 0 0501[tiab] OR p 0 0502[tiab] OR p 0 0503[tiab] OR p 0 0504[tiab] OR p 0 0505[tiab] OR p 0 0505385[tiab] OR p 0 0506[tiab] OR p 0 0507[tiab] OR p 0 0508[tiab] OR p 0 0509[tiab] OR p 0 051[tiab] OR p 0 0510[tiab] OR p 0 0511[tiab] OR p 0 0512[tiab] OR p 0 0513[tiab] OR p 0 0514[tiab] OR p 0 0515[tiab] OR p 0 0516[tiab] OR p 0 0517[tiab] OR p 0 0518[tiab] OR p 0 0519[tiab] OR p 0 052[tiab] OR p 0 0520[tiab] OR p 0 0522[tiab] OR p 0 0523[tiab] OR p 0 0524[tiab] OR p 0 0525[tiab] OR p 0 052574[tiab] OR p 0 0526[tiab] OR p 0 0527[tiab] OR p 0 0529[tiab] OR p 0 053[tiab] OR p 0 0530[tiab] OR p 0 0531[tiab] OR p 0 0532[tiab] OR p 0 0533[tiab] OR p 0 0534[tiab] OR p 0 0535[tiab] OR p 0 0536[tiab] OR p 0 0537[tiab] OR p 0 0539[tiab] OR p 0 054[tiab] OR p 0 0540[tiab] OR p 0 0541[tiab] OR p 0 0542[tiab] OR p 0 0543[tiab] OR p 0 0544[tiab] OR p 0 0545[tiab] OR p 0 0546[tiab] OR p 0 0547[tiab] OR p 0 0548[tiab] OR p 0 0549[tiab] OR p 0 055[tiab] OR p 0 0550[tiab] OR p 0 0551[tiab] OR p 0 0552[tiab] OR p 0 0553[tiab] OR p 0 0554[tiab] OR p 0 05548[tiab] OR p 0 0556[tiab] OR p 0 0557[tiab] OR p 0 0558[tiab] OR p 0 0559[tiab] OR p 0 056[tiab] OR p 0 0560[tiab] OR p 0 0561[tiab] OR p 0 0562[tiab] OR p 0 0563[tiab] OR p 0 0564[tiab] OR p 0 0566[tiab] OR p 0 0567[tiab] OR p 0 0568[tiab] OR p 0 0569[tiab] OR p 0 057[tiab] OR p 0 0570[tiab] OR p 0 0571[tiab] OR p 0 0572[tiab] OR p 0 0573[tiab] OR p 0 0574[tiab] OR p 0 0575[tiab] OR p 0 0576[tiab] OR p 0 05760[tiab] OR p 0 0577[tiab] OR p 0 0578[tiab] OR p 0 0579[tiab] OR p 0 058[tiab] OR p 0 0580[tiab] OR p 0 0581[tiab] OR p 0 0582[tiab] OR p 0 0583[tiab] OR p 0 0584[tiab] OR p 0 05846[tiab] OR p 0 0585[tiab] OR p 0 0586[tiab] OR p 0 0587[tiab] OR p 0 0588[tiab] OR p 0 0589[tiab] OR p 0 05891[tiab] OR p 0 059[tiab] OR p 0 0590[tiab] OR p 0 0591[tiab] OR p 0 0592[tiab] OR p 0 0593[tiab] OR p 0 0594[tiab] OR p 0 0595[tiab] OR p 0 0596[tiab] OR p 0 0597[tiab] OR p 0 0598[tiab] OR p 0 0599[tiab])
# p-value bin 0.06: (p=.06*[tiab] OR p=0.06*[tiab])
# common tests: (t-test[tiab] OR anova[tiab] OR ancova[tiab] OR "mixed model"[tiab])
# atypical tests: (nonparametric[tiab] OR non-parametric[tiab] OR wlicoxon-rank[tiab] OR "wilcoxon rank"[tiab] OR kruskal-wallis[tiab] OR "kruskal wallis"[tiab] OR transformation[tiab] OR (outlier*[tiab] AND remov*[tiab]))
```


Asterisks in PubMed are used to indicate wildcards. PubMed returns wildcards and shows the terms returned for manual inspection. Expansion of the 0.05\* term above shows these wildcards expanded. Search 0.05* is expanded to remove inclusion of the commonly found mention of p < 0.05 in abstracts. PubMed interprets any equality characters (<, =, >) as blank spaces. An asterisk alone could not be used here, as we needed to manually remove references to 0.05. These are not likely to represent values in a bin, because they could represent the entire inequality of p < 0.05 or reference to a significance level threshold.


### PubMed query data file and image

A screenshot of the search query conducted on 8/25/14 has been added to assist with clarity and transparency. A .csv file with these data plus extractions times also has been added. This was exported by PubMed after the search. The date column was added manually, as PubMed does not include this in the export of searches. 


__File name for query image:__ conference_materials_2014_query_image.pdf


__File name for query export:__ conference_materials_2014_query.csv


__Definitions of column headings__

Column Heading      | Definition                            | Possible Values 
------------------- | ------------------------------------- | ---------------------
search              | Search number                         |
query               | Query used to search PubMed           |
items               | Number of articles found by search query |
time                | Time search was conducted (U.S.A. Central Time) |
date                | Date of search                        |
trial               | Study trial                           | org = original trial
method              | Search string method                  | a = method a
database            | Database data were collected from     | pm = PubMed


### Analysis code

__File name for analysis code:__ conference_materials_2014_code.R


__Study level naming convention:__ database_method_trial_mode

* database: pm = PubMed
* method: a = method a
* trial: org = original
* mode: man = manual search


__Analysis level naming convention:__ study_function 

* study: pm_a_org_man
* function: xsq = chisq.test; pd = percentage deviation 


## A Note on How to Replicate this Study 

Because data were extracted from PubMed manually on a specific date, one would need to download PubMed history and assess the literature from the point in time noted in the data file, using the methods described in this document. Another option might be to run the search described herein and subtract dates from the date reported in our data file. We have not done this ourselves. However, future work will attempt to replicate these findings in the same literature set at a later date. 


## Author Contribution 

Dr. Kroeger conducted the study, refined the methods, analyzed data, made the poster, and created the open science documents for the repository. Dr. Brown provided editorial assistance with methods, poster preparation, and open science documents. Dr. Allison originated the study, provided editorial assistance with the presentation, and is the senior author of the presentation.


## License Information 

These materials are licensed under the Creative Commons Attribution Share Alike 4.0.

__File name for analysis code:__ LICENSE.txt


## Citation Information

### Recommended citation for Conference Materials 2014

Please use the following to cite any of the supporting materials herein: 

Kroeger CM, Brown AW. Data and analysis code from published abstract: Evidence of p-value fiddling using a rapid, high-volume, systematic method. Zenodo. 2018. DOI:


### Recommended citation for published 2014 abstract 

Please use the following to cite the published abstract: 

Kroeger CM, Brown AW, Allison DB. Evidence of p-value fiddling using a rapid, high-volume, systematic method. American Society for Nutrition (ASN): Advances and Controversies in Clinical Nutrition Annual Scientific Meeting. National Harbor, Maryland, USA, 2014.
